version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-filament
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: filament
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - filament_net
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin_filament
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - filament_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  filament_net:
    driver: bridge

